Your scheduled DataDoc [{{ data_doc_title }}]({{ doc_url }}) has been disabled due to the following reason:

**{{ disabled_reason }}**

You can re-enable the scheduled doc by going to the URL and configure the workflow on the bottom right corner.
